/**
 * Remediation — generate the files that fix what the audit found.
 *
 * A report that ends at "here is what is wrong" pushes the hard part back onto
 * the customer. The hard part is knowing exactly which token to write on which
 * line, and that is precisely the knowledge they came here lacking. So the audit
 * ends with files they can paste.
 *
 * The generated robots.txt implements the citation-only posture by default,
 * because it is the right answer for the overwhelming majority of commercial
 * sites: every crawler that can cite you is allowed, and every crawler that only
 * trains on you is refused. It also preserves the site's existing non-AI rules,
 * which are usually there for a reason we cannot see from outside.
 *
 * @module core/remediate
 */

import { AGENTS } from './registry.js';

/** @typedef {import('./types.js').Remediation} Remediation */
/** @typedef {import('./types.js').AgentVerdict} AgentVerdict */
/** @typedef {import('./types.js').RobotsDocument} RobotsDocument */
/** @typedef {import('./types.js').Finding} Finding */
/** @typedef {import('./html.js').PageAnalysis} PageAnalysis */

/**
 * @typedef {'citation-only' | 'open' | 'closed'} PolicyChoice
 */

/**
 * @param {object} input
 * @param {RobotsDocument} input.robots
 * @param {AgentVerdict[]} input.verdicts
 * @param {PageAnalysis} input.page
 * @param {Finding[]} input.findings
 * @param {string} input.origin
 * @param {PolicyChoice} [input.policy]
 * @returns {Remediation}
 */
export function buildRemediation({ robots, verdicts, page, findings, origin, policy = 'citation-only' }) {
  return {
    robotsTxt: generateRobotsTxt({ robots, origin, policy }),
    llmsTxt: generateLlmsTxt({ page, origin }),
    jsonLd: generateJsonLd({ page, origin }),
    steps: generateSteps(findings, verdicts),
  };
}

/**
 * Produce a complete robots.txt implementing the chosen policy.
 *
 * Non-AI rules from the existing file are carried over verbatim. We are not in
 * a position to judge why a site disallows `/admin`, so we do not touch it.
 *
 * @param {{ robots: RobotsDocument, origin: string, policy: PolicyChoice }} input
 * @returns {string}
 */
export function generateRobotsTxt({ robots, origin, policy }) {
  const aiTokens = new Set(AGENTS.map((a) => a.token.toLowerCase()));
  const preserved = robots.groups.filter(
    (g) => !g.agents.every((a) => aiTokens.has(a) || a === '*'),
  );
  const wildcard = robots.groups.find((g) => g.agents.includes('*'));

  /** @type {string[]} */
  const out = [];
  out.push('# robots.txt generated by Sightline');
  out.push(`# Policy: ${policyDescription(policy)}`);
  out.push('#');
  out.push('# The crawlers below are grouped by what they actually do. Blocking a');
  out.push('# training crawler costs you no visibility. Blocking a search or');
  out.push('# user-triggered crawler removes you from AI answers entirely.');
  out.push('');

  if (policy === 'closed') {
    out.push('# Every AI crawler is refused.');
    for (const agent of AGENTS) {
      out.push(`User-agent: ${agent.token}`);
    }
    out.push('Disallow: /');
    out.push('');
  } else {
    const search = AGENTS.filter((a) => a.purpose === 'search' || a.purpose === 'user');
    out.push('# --- Answer engines: allowed, so they can cite you ---');
    for (const agent of search) {
      out.push(`# ${agent.token} — ${agent.product}`);
    }
    out.push('');
    for (const agent of search) {
      out.push(`User-agent: ${agent.token}`);
    }
    out.push('Allow: /');
    out.push('');

    if (policy === 'citation-only') {
      const training = AGENTS.filter((a) => a.purpose === 'training');
      out.push('# --- Training crawlers: refused, at zero cost to your visibility ---');
      for (const agent of training) {
        out.push(`User-agent: ${agent.token}`);
      }
      out.push('Disallow: /');
      out.push('');
      out.push('# Note: Bytespider has a documented history of ignoring robots.txt.');
      out.push('# If you need it stopped, enforce at your CDN or WAF as well.');
      out.push('');
    }
  }

  out.push('# --- Everything else ---');
  out.push('User-agent: *');
  if (wildcard && wildcard.rules.length > 0) {
    for (const rule of wildcard.rules) {
      out.push(`${rule.type === 'allow' ? 'Allow' : 'Disallow'}: ${rule.path}`);
    }
  } else {
    out.push('Allow: /');
  }
  out.push('');

  if (preserved.length > 0) {
    out.push('# --- Your existing rules, preserved unchanged ---');
    for (const group of preserved) {
      for (const agent of group.agents) out.push(`User-agent: ${agent}`);
      for (const rule of group.rules) {
        out.push(`${rule.type === 'allow' ? 'Allow' : 'Disallow'}: ${rule.path}`);
      }
      if (group.crawlDelay !== null) out.push(`Crawl-delay: ${group.crawlDelay}`);
      out.push('');
    }
  }

  const sitemaps = robots.sitemaps.length > 0 ? robots.sitemaps : [`${origin}/sitemap.xml`];
  for (const sitemap of sitemaps) out.push(`Sitemap: ${sitemap}`);
  out.push('');

  return out.join('\n');
}

/**
 * @param {PolicyChoice} policy
 * @returns {string}
 */
function policyDescription(policy) {
  switch (policy) {
    case 'citation-only':
      return 'allow every crawler that can cite you, refuse every crawler that only trains on you';
    case 'open':
      return 'allow all AI crawlers';
    case 'closed':
      return 'refuse all AI crawlers';
    default:
      return 'custom';
  }
}

/**
 * Draft an llms.txt seeded from what the page already tells us.
 *
 * @param {{ page: PageAnalysis, origin: string }} input
 * @returns {string}
 */
export function generateLlmsTxt({ page, origin }) {
  const host = safeHost(origin);
  const name = page.openGraph['og:site_name'] ?? deriveName(page.title) ?? host;
  const summary =
    page.description ?? page.openGraph['og:description'] ?? `Information about ${name}.`;

  return [
    `# ${name}`,
    '',
    `> ${summary}`,
    '',
    '## Core pages',
    '',
    `- [Home](${origin}/): Overview of ${name}.`,
    `- [About](${origin}/about): Who we are, what we do, and who we serve.`,
    `- [Contact](${origin}/contact): How to get in touch.`,
    '',
    '## Products and services',
    '',
    `- [Products](${origin}/products): What we offer, with pricing where published.`,
    '',
    '## Reference',
    '',
    `- [FAQ](${origin}/faq): Questions we are asked most often, answered directly.`,
    '',
    '## Notes',
    '',
    `- Replace these placeholder links with the pages you most want AI assistants to`,
    `  read and cite. Fewer, better-chosen pages outperform an exhaustive list.`,
    `- Each description should state plainly what a reader will find on that page.`,
    '',
  ].join('\n');
}

/**
 * Draft Organization JSON-LD, keeping whatever the page already asserts.
 *
 * @param {{ page: PageAnalysis, origin: string }} input
 * @returns {string}
 */
export function generateJsonLd({ page, origin }) {
  const host = safeHost(origin);
  const name = page.openGraph['og:site_name'] ?? deriveName(page.title) ?? host;
  const description = page.description ?? page.openGraph['og:description'] ?? '';

  return JSON.stringify(
    {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name,
      url: origin,
      ...(description ? { description } : {}),
      logo: `${origin}/logo.png`,
      sameAs: [
        'https://www.linkedin.com/company/your-company',
        'https://x.com/your-company',
      ],
      contactPoint: {
        '@type': 'ContactPoint',
        contactType: 'customer service',
        url: `${origin}/contact`,
      },
    },
    null,
    2,
  );
}

/**
 * Turn findings into an ordered plan. Ordering is by consequence, so the first
 * item is always the one that costs the most to leave alone.
 *
 * @param {Finding[]} findings
 * @param {AgentVerdict[]} verdicts
 * @returns {string[]}
 */
function generateSteps(findings, verdicts) {
  /** @type {string[]} */
  const steps = [];

  const blockedReach = verdicts.filter((v) => !v.allowed && v.agent.reachWeight > 0);
  if (blockedReach.length > 0) {
    const worst = [...blockedReach].sort((a, b) => b.agent.reachWeight - a.agent.reachWeight);
    steps.push(
      `Unblock the answer engines. ${worst.map((v) => v.agent.token).join(', ')} ${worst.length === 1 ? 'is' : 'are'} currently refused; replacing your robots.txt with the generated version restores ${worst.length === 1 ? 'it' : 'them'}.`,
    );
  }

  const edge = verdicts.filter((v) => v.blockedBy === 'http');
  if (edge.length > 0) {
    steps.push(
      `Whitelist ${edge.map((v) => v.agent.token).join(', ')} in your CDN or WAF. Your robots.txt already allows them, but the server is refusing the request before robots.txt is ever consulted.`,
    );
  }

  if (findings.some((f) => f.id === 'client-side-rendering')) {
    steps.push(
      'Server-render your pages. This is the largest single change available to you: without it, every crawler that does not execute JavaScript receives an empty document no matter what else you fix.',
    );
  }

  if (findings.some((f) => f.id === 'meta-noindex')) {
    steps.push('Remove the noindex meta tag from this page.');
  }

  if (findings.some((f) => f.id === 'no-structured-data' || f.id === 'no-entity-schema')) {
    steps.push('Add the generated Organization JSON-LD sitewide, then a page-level type on each template.');
  }

  if (findings.some((f) => f.id === 'no-llms-txt')) {
    steps.push('Publish the generated llms.txt at your site root and edit it to list your real key pages.');
  }

  if (findings.some((f) => f.id === 'no-sitemap-declared')) {
    steps.push('Declare your sitemap in robots.txt so answer engines can discover pages without crawling blind.');
  }

  if (steps.length === 0) {
    steps.push('No structural changes needed. Re-audit after any change to robots.txt, your CDN rules, or your rendering strategy.');
  }

  return steps;
}

/**
 * Strip a trailing brand suffix from a page title: "Acme Ltd — Home" → "Acme Ltd".
 *
 * @param {string|null} title
 * @returns {string|null}
 */
function deriveName(title) {
  if (!title) return null;
  const parts = title.split(/\s+[|–—-]\s+/);
  const candidate = (parts.length > 1 ? parts[parts.length - 1] : parts[0]) ?? title;
  const trimmed = candidate.trim();
  return trimmed === '' ? null : trimmed;
}

/**
 * @param {string} origin
 * @returns {string}
 */
function safeHost(origin) {
  try {
    return new URL(origin).host;
  } catch {
    return origin;
  }
}
