import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import propertiesRouter from "./properties";
import phasesRouter from "./phases";
import tasksRouter from "./tasks";
import costItemsRouter from "./cost_items";
import scenarioConfigsRouter from "./scenario_configs";
import financialsRouter from "./financials";
import dashboardRouter from "./dashboard";
import intelligenceRouter from "./intelligence";
import decisionsRouter from "./decisions";
import optimisationRouter from "./optimisation";
import costOptimisationRulesRouter from "./cost_optimisation_rules";
import complianceRouter from "./compliance";
import aiRouter from "./ai";
import fixedCostItemsRouter from "./fixed_cost_items";
import bedhamptonRouter from "./bedhampton";
import lifestyleRouter from "./lifestyle";
import marketingRouter from "./marketing";
import competitionRouter from "./competition";
import resetRouter from "./reset";
import risksRouter from "./risks";
import suppliersRouter from "./suppliers";
import investmentsRouter from "./investments";
import riskIntelligenceRouter from "./risk-intelligence";
import timelineRouter from "./timeline";
import tenderRouter from "./tender";
import digestRouter from "./digest";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(propertiesRouter);
router.use(phasesRouter);
router.use(tasksRouter);
router.use(costItemsRouter);
router.use(scenarioConfigsRouter);
router.use(financialsRouter);
router.use(dashboardRouter);
router.use(intelligenceRouter);
router.use(decisionsRouter);
router.use(optimisationRouter);
router.use(costOptimisationRulesRouter);
router.use(complianceRouter);
router.use(aiRouter);
router.use(fixedCostItemsRouter);
router.use(bedhamptonRouter);
router.use(lifestyleRouter);
router.use(marketingRouter);
router.use(competitionRouter);
router.use(resetRouter);
router.use(risksRouter);
router.use(suppliersRouter);
router.use(investmentsRouter);
router.use(riskIntelligenceRouter);
router.use(timelineRouter);
router.use(tenderRouter);
router.use(digestRouter);

export default router;
