/**
 * V8 Migration — rebuild Winchester clinic tracker from scratch.
 *
 * Idempotent guard: checks whether phase "Pre-Lease Due Diligence" with
 * status='active' already exists. If yes, skips entirely.
 *
 * What it does:
 *  1. Archives all existing phases for the project (ARCHIVED: prefix + status='archived')
 *  2. Creates 12 new active phases (sort_order 1–12)
 *  3. Inserts all 111 tasks across those phases
 */

import { db } from "./index";
import * as schema from "./schema";
import { eq, and, sql } from "drizzle-orm";

export async function runV8Migration(projectId: number): Promise<void> {
  const guard = await db
    .select()
    .from(schema.phasesTable)
    .where(
      and(
        eq(schema.phasesTable.projectId, projectId),
        eq(schema.phasesTable.name, "Pre-Lease Due Diligence"),
        eq(schema.phasesTable.status, "active")
      )
    );

  if (guard.length > 0) {
    return;
  }

  console.log("🔧 Running V8 migration: rebuilding Winchester tracker from master task list (111 tasks, 12 phases)…");

  await db.execute(
    sql`UPDATE launch_phases
        SET status = 'archived',
            name = CASE WHEN name NOT LIKE 'ARCHIVED:%' THEN 'ARCHIVED: ' || name ELSE name END
        WHERE project_id = ${projectId} AND status != 'archived'`
  );

  type PhaseInsert = typeof schema.phasesTable.$inferInsert;
  type TaskInsert = typeof schema.tasksTable.$inferInsert;

  const PHASES: { phase: Omit<PhaseInsert, "projectId" | "id" | "createdAt" | "updatedAt">; tasks: Omit<TaskInsert, "phaseId" | "id" | "createdAt" | "updatedAt">[] }[] = [
    {
      phase: { name: "Pre-Lease Due Diligence", description: "Planning and research before lease commitment", sortOrder: 1, status: "active" },
      tasks: [
        { title: "Search WCC Public Access — s.106, conditions, Article 4 Directions", owner: "David", status: "complete", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 1, notes: "Confirm any planning restrictions, Article 4 directions, historical constraints or conditions affecting the unit." },
        { title: "Confirm Use Class E(e) — clinic use position", owner: "David / Design Lead", status: "in_progress", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 2, notes: "Confirm internal aesthetics clinic use is acceptable under Class E. Keep separate from signage/frontage consent." },
        { title: "Listed Building / Conservation Context Check", owner: "David / Design Lead / Solicitor", status: "in_progress", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Check whether conservation area, neighbouring listed building context or frontage constraints affect signage, painting, fixings or external works." },
        { title: "Check Local Authority Licensing — Health and Care Act 2022", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 200, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 4, notes: "Confirm no additional local licensing requirement is triggered by the proposed aesthetics clinic activity." },
        { title: "Check Rateable Value and Business Rates Position", owner: "David", status: "in_progress", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 5, notes: "Confirm rateable value, multiplier, transitional relief if any, and expected monthly rates liability after occupation." },
        { title: "Negotiate Heads of Terms with Agent/Landlord", owner: "David", status: "in_progress", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 6, notes: "Lock rent, rent-free period, deposit, break clause, landlord consent process, repairing obligations and VAT on rent." },
      ],
    },
    {
      phase: { name: "Legal, Lease & Handover", description: "Solicitors, lease, RICS and completion", sortOrder: 2, status: "active" },
      tasks: [
        { title: "Commercial Property Solicitor — Lease Negotiation", owner: "Solicitor", status: "in_progress", riskLevel: "low", costTier: "mid", costLow: 2000, costMid: 3500, costHigh: 5500, selectedCost: 3500, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance / confirm quote", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 1, notes: "Legal work for commercial lease review, negotiation, reporting and completion." },
        { title: "Solicitor Scope Clarification", owner: "David / Solicitor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — admin task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 2, notes: "Confirm exactly what the solicitor fee includes: lease negotiation, licence for alterations, schedule of condition annexing, completion statement and landlord solicitor liaison." },
        { title: "Lease Repairing Obligation Review", owner: "Solicitor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 750, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "included in solicitor allowance unless separately quoted", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included inside another package", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Must clarify FRI exposure and ensure Schedule of Condition protects Abi Peters Aesthetics." },
        { title: "Landlord Alterations Rights Review", owner: "Solicitor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 500, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "included in solicitor allowance unless separately quoted", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included inside another package", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 4, notes: "Confirm what alterations require consent and whether licence for alterations is needed for partitions, basins, signage and fixings." },
        { title: "RICS Schedule of Condition", owner: "RICS Surveyor", status: "in_progress", riskLevel: "low", costTier: "mid", costLow: 800, costMid: 1500, costHigh: 2500, selectedCost: 1500, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance / confirm quote", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 5, notes: "Must be completed and annexed to the lease before signing to limit repairing liability under FRI lease." },
        { title: "Exchange and Complete Lease", owner: "Solicitor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — completion milestone", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 6, notes: "Milestone only. Completion must include Schedule of Condition annexed and VAT on rent confirmed." },
        { title: "Rent Deposit / Lease Cash Requirement", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 2708, costMid: 2708, costHigh: 8124, selectedCost: 2708, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "no VAT expected unless confirmed otherwise", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 7, notes: "One-month deposit planning assumption. Increase manually if final Heads of Terms require three months." },
        { title: "Rent-Free / Fit-Out Period Cashflow Planning — 2 Months", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no spend if rent-free granted", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 8, notes: "Rent-free period protects cashflow during fit-out. Does not remove insurance, utilities, business rates or fit-out spend." },
      ],
    },
    {
      phase: { name: "Design, Approvals & Procurement", description: "Design, planning consents, contractor procurement", sortOrder: 3, status: "active" },
      tasks: [
        { title: "Appoint Design / Building Regulations Lead", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 800, costMid: 2400, costHigh: 4000, selectedCost: 2400, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 1, notes: "Technician-led design/building regulations package. Must include measured survey/drawings, proposed layout and building regulations detail sufficient for contractor pricing and approval." },
        { title: "Confirm Planning / Conservation / Advertisement Consent Position", owner: "Design Lead + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 500, costHigh: 2500, selectedCost: 500, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 2, notes: "Separate internal Class E use from external signage/frontage/conservation matters." },
        { title: "Produce Employer's Requirements / Contractor Fit-Out Brief", owner: "David + Design Lead", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 500, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — admin/specification task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Create clear scope for contractor pricing." },
        { title: "Contractor Site Survey and Buildability Review", owner: "Main Contractor / Project Manager", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 500, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "included in contractor quote / N/A", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 4, notes: "Contractor verifies ceiling void, existing electrics, drainage routes, ventilation, fire alarm, emergency lighting and access." },
        { title: "Tender / Quote Managed Fit-Out Package", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — procurement task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 5, notes: "Procurement task only. Actual build cost captured in building works lines." },
        { title: "Final Scope Lock and Fixed Cost Agreement", owner: "David + Main Contractor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — admin/contract decision", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 6, notes: "Lock drawings, specification, inclusions, exclusions, VAT position, payment milestones and variation process before works start." },
        { title: "Licence for Alterations", owner: "Solicitor + David + Design Lead / Contractor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 600, costMid: 1200, costHigh: 3500, selectedCost: 1200, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 7, notes: "Covers landlord consent support for partitions, basins, electrics, signage fixings, shopfront repaint and any penetrations." },
        { title: "Building Control Submission / Initial Notice", owner: "Design Lead / Building Control / Approved Inspector", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 400, costMid: 900, costHigh: 2500, selectedCost: 900, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 8, notes: "Building regulations route for internal works. Do not duplicate with another Building Notice line." },
        { title: "Advertisement Consent — Shopfront / Signage", owner: "David / Signage Supplier / Design Lead", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 168, costMid: 350, costHigh: 700, selectedCost: 350, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 9, notes: "Allowance for signage/advert consent if required due to conservation area and shopfront works." },
      ],
    },
    {
      phase: { name: "Managed Building Works", description: "Fit-out construction programme", sortOrder: 4, status: "active" },
      tasks: [
        { title: "Contractor Pre-Start Meeting and Programme Confirmation", owner: "Main Contractor + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — admin task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 1, notes: "Confirm programme, access, responsibilities, certificates, inspection points and handover requirements." },
        { title: "Main Contractor Fit-Out Package — Internal Works", owner: "Contractor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 18000, costMid: 21500, costHigh: 30000, selectedCost: 21500, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 2, notes: "Lean core build package. Includes enabling, partitions, coordination, basic making good, doors/linings and contractor management. Does not double count separate electrical, plumbing, flooring, decoration or joinery lines unless contractor quote later includes them." },
        { title: "Electrical Works", owner: "Contractor / Qualified Electrician", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 3000, costMid: 4800, costHigh: 7000, selectedCost: 4800, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 3, notes: "Treatment room sockets, lighting changes, emergency lighting implications, certification. If included in contractor package later, set this line to included inside another package." },
        { title: "Plumbing / Clinical Basin Works", owner: "Contractor / Qualified Plumber", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 2000, costMid: 4200, costHigh: 6000, selectedCost: 4200, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 4, notes: "Two clinical basins, hot/cold supply, waste, isolation and coordination with cabinetry." },
        { title: "Clinical Flooring Package", owner: "Contractor / Specialist Flooring Installer", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1500, costMid: 3200, costHigh: 4500, selectedCost: 3200, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 5, notes: "Clinical vinyl to treatment areas only unless final quote expands scope." },
        { title: "Internal Decoration and Finishing", owner: "Contractor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1000, costMid: 1800, costHigh: 3000, selectedCost: 1800, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 6, notes: "Clean premium finish, not luxury decorative scheme." },
        { title: "Joinery / Reception Desk / Clinical Cabinetry — Decision", owner: "David + Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — decision task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 7, notes: "Decide whether family joinery, contractor joinery, or hybrid." },
        { title: "Joinery / Reception Desk / Clinical Cabinetry — Installation", owner: "Contractor / Joinery Supplier / Family Joinery", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1500, costMid: 3000, costHigh: 6000, selectedCost: 3000, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 8, notes: "Tight allowance. Simple reception/joinery only. Avoid bespoke overspend." },
        { title: "Wall Panelling / Decorative Moulding Feature Finish", owner: "Contractor / Joinery Supplier", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 5000, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "included inside contractor/joinery allowance unless separately approved", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included inside another package", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 9, notes: "Do not assign separate cost unless David approves upgrade." },
        { title: "Door Furniture, Room Labels and Black Ironmongery", owner: "Contractor / Signage Supplier", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 1500, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "included inside contractor/joinery/signage allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included inside another package", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 10, notes: "Keep visible but do not double count." },
        { title: "Shopfront Repaint", owner: "External Decorator / Contractor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1000, costMid: 1200, costHigh: 2500, selectedCost: 1200, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance / confirm quote", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 11, notes: "Repaint purple frontage to off-white/white and refresh dark detailing. Must follow landlord/signage consent." },
        { title: "External Signage Package", owner: "Signage Supplier", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 900, costMid: 1800, costHigh: 3000, selectedCost: 1800, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 12, notes: "Keep simple and non-overdesigned unless separately approved." },
      ],
    },
    {
      phase: { name: "FF&E, Equipment & Clinic Styling", description: "Furniture, equipment and clinic interior", sortOrder: 5, status: "active" },
      tasks: [
        { title: "Treatment Couch x1", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1707, costMid: 2438, costHigh: 3657, selectedCost: 2438, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 1, notes: "Couch only. Does not include full treatment room equipment." },
        { title: "Internal Signage and Branding Package", owner: "David + Signage Supplier", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 500, costMid: 900, costHigh: 2500, selectedCost: 900, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 2, notes: "Reception wall logo, door plaques, basic room signs. Not a full graphics programme." },
        { title: "Reception Furniture and Styling Package", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 800, costMid: 1200, costHigh: 3000, selectedCost: 1200, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 3, notes: "Lean premium reception styling using off-the-shelf items." },
        { title: "Consultation Room Furniture and Styling Package", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 500, costMid: 900, costHigh: 2000, selectedCost: 900, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 4, notes: "Chairs, table, simple premium finish." },
        { title: "Treatment Room Furniture, Equipment and Styling Package", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1500, costMid: 3200, costHigh: 6000, selectedCost: 3200, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 5, notes: "Stool, trolley, bins, mirrors, basic storage accessories, styling. Excludes treatment couch." },
        { title: "Product Display / Retail Shelving / LED Setup", owner: "Abi + David / Joinery Supplier", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 250, costMid: 750, costHigh: 2500, selectedCost: 750, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 6, notes: "Lean display only. Upgrade later if needed." },
        { title: "Wall Art, Certificates and Picture Lighting", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 250, costMid: 500, costHigh: 1500, selectedCost: 500, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 7, notes: "Lean artwork/certificates allowance. Picture lights only if budget allows." },
        { title: "Furniture / Equipment Installation and Room Dressing", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — admin/setup task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 8, notes: "Installation/setup task only. Costs captured in FF&E lines." },
      ],
    },
    {
      phase: { name: "Clinical Governance & Compliance", description: "Policies, protocols and clinical readiness", sortOrder: 6, status: "active" },
      tasks: [
        { title: "CPD Documentation Log", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 1, notes: "Set up clinical CPD evidence log." },
        { title: "ACE Membership — Confirm Winchester Cover", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 2, notes: "Confirm existing professional membership/cover position." },
        { title: "BLS Certification — Confirm Current", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost unless renewal needed", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Confirm valid within required timeframe." },
        { title: "DBS Check", owner: "Abi", status: "in_progress", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 38, costHigh: 80, selectedCost: 38, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 4, notes: "Enhanced disclosure if required." },
        { title: "NMC Face-to-Face Prescribing SOP", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 5, notes: "Written procedure for Winchester." },
        { title: "Complaints and Incident Log", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 6, notes: "Set up before opening." },
        { title: "Batch Number and Traceability Log", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 7, notes: "Required for injectable traceability." },
        { title: "Adverse Event Protocol", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 56, costMid: 80, costHigh: 120, selectedCost: 80, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 8, notes: "Vascular occlusion, anaphylaxis, vasovagal and emergency response procedure." },
        { title: "Sharps Safety Policy", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 9, notes: "Written policy." },
        { title: "IPC Policy", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 10, notes: "Written infection prevention and control policy for 9A." },
        { title: "COSHH Risk Assessments", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 11, notes: "COSHH for relevant substances used in clinic." },
        { title: "Consent Forms and Questionnaires — Winchester Setup", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 12, notes: "Configure forms in clinic management software." },
        { title: "Delegation and Supervision Policy", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 13, notes: "Required before any second practitioner model." },
        { title: "JCCP Practitioner Register", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost unless fee applies", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 14, notes: "Apply online if required/desired." },
        { title: "Save Face Registration", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 500, costMid: 700, costHigh: 900, selectedCost: 700, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 15, notes: "Online application and clinic assessment if continuing with Save Face." },
        { title: "Clinical Waste Contract", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 399, costMid: 570, costHigh: 855, selectedCost: 570, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 16, notes: "Licensed clinical waste carrier." },
        { title: "Fire Risk Assessment — Post Fit-Out", owner: "Fire Assessor + Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 332, costMid: 475, costHigh: 712, selectedCost: 475, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 17, notes: "Full written FRA after fit-out." },
        { title: "Emergency Drugs and Equipment Kit", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 140, costMid: 200, costHigh: 300, selectedCost: 200, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 18, notes: "Emergency drugs/equipment setup." },
        { title: "Baseline Photography Protocol", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 21, costMid: 30, costHigh: 45, selectedCost: 30, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 19, notes: "Standardised clinical photography protocol." },
        { title: "Final Clinical Readiness Check", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — admin task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 20, notes: "Confirm rooms, documents, equipment, emergency kit, waste, forms and patient flow before launch." },
      ],
    },
    {
      phase: { name: "Stock, Suppliers & Clinical Setup", description: "Stock, suppliers and clinical consumables", sortOrder: 7, status: "active" },
      tasks: [
        { title: "Allergan Practitioner Pathway — Notify Winchester", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 1, notes: "Notify or update address as required." },
        { title: "Allergan Direct — Register 9A Delivery Address", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 2, notes: "Supplier delivery setup." },
        { title: "Galderma / Azzalure — Register Jewry Street Delivery Address", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Supplier delivery setup." },
        { title: "Derma Focus / Polynucleotides — Register Jewry Street", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 4, notes: "Supplier location update." },
        { title: "Opening Injectable Stock", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 3000, costMid: 4250, costHigh: 6500, selectedCost: 4250, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance / supplier dependent", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 5, notes: "Opening injectable stock only. Keep lean initially." },
        { title: "Clinical Smallwares and Consumables", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 750, costMid: 1000, costHigh: 3000, selectedCost: 1000, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 6, notes: "Gloves, gauze, couch roll, disinfectant, sharps containers, disposables, aftercare materials." },
        { title: "Retail / Skincare Opening Stock", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1000, costMid: 2000, costHigh: 8000, selectedCost: 1000, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance / supplier dependent", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 7, notes: "Lean opening retail stock. Extra retail stock is a stretch/deferred item." },
      ],
    },
    {
      phase: { name: "Finance, Insurance & Admin", description: "Finance, insurance, utilities and admin setup", sortOrder: 8, status: "active" },
      tasks: [
        { title: "Accounting Software — Xero or QuickBooks", owner: "David", status: "complete", riskLevel: "low", costTier: "mid", costLow: 120, costMid: 300, costHigh: 420, selectedCost: 300, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 1, notes: "Keep existing accounting system live and ready for Winchester cost tracking." },
        { title: "Clinic Management Software — Check ANS Plan", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — included in existing software unless plan changes", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 2, notes: "Check ANS setup for Winchester location." },
        { title: "ICO Data Protection Fee", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 33, costMid: 47, costHigh: 70, selectedCost: 47, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "no VAT expected / confirm", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 3, notes: "Register/pay data protection fee as controller." },
        { title: "Hamilton Fraser / Indemnity / Premises Insurance", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 1330, costMid: 1900, costHigh: 2850, selectedCost: 1900, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "inc VAT planning allowance / confirm", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 4, notes: "Update indemnity and add premises insurance." },
        { title: "Register for Business Rates", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — admin task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 5, notes: "Notify Winchester City Council after occupation." },
        { title: "Notify Utilities — Electricity, Water, Broadband", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — setup admin", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 6, notes: "Take meter readings at handover and arrange supplier accounts." },
        { title: "Broadband Availability / Setup", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 100, costHigh: 300, selectedCost: 100, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 7, notes: "Check broadband availability and setup." },
        { title: "Air Conditioning Inspection / Service", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 192, costMid: 275, costHigh: 412, selectedCost: 275, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 8, notes: "Inspect/service existing AC." },
        { title: "Legionella Risk Assessment", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 122, costMid: 175, costHigh: 262, selectedCost: 175, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 9, notes: "Water safety assessment." },
        { title: "PAT Testing Setup", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 35, costMid: 50, costHigh: 75, selectedCost: 50, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 10, notes: "PAT testing arrangements for equipment." },
        { title: "Card Payment Terminal for Winchester", owner: "David", status: "deferred", riskLevel: "low", costTier: "mid", costLow: 29, costMid: 69, costHigh: 149, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "deferred / not in launch cap", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "Deferred / not in launch cap", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 11, notes: "Use existing payment solution initially if possible." },
        { title: "Klarna — Set Up Winchester", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 12, notes: "Admin setup only." },
        { title: "VAT Registration Monitoring", owner: "Accountant + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — monitoring task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 13, notes: "Monitor rolling 12-month taxable turnover and registration trigger." },
      ],
    },
    {
      phase: { name: "Marketing & Launch", description: "Digital, advertising and launch campaign", sortOrder: 9, status: "active" },
      tasks: [
        { title: "Winchester SEO — Treatment Landing Pages", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — David-led", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 1, notes: "Build SEO base 3-6 months ahead." },
        { title: "Website — Winchester Page, Photos, Privacy Notice", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 150, costHigh: 500, selectedCost: 150, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 2, notes: "Add Winchester page and privacy/location updates." },
        { title: "Winchester BID Registration", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "N/A — admin task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Register if relevant." },
        { title: "Google Business Profile — Winchester Location", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — no cost", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 4, notes: "Create/verify GBP for new location." },
        { title: "Google Tag Manager / Conversion Tracking", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — David-led", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 5, notes: "Ensure bookings/leads are tracked." },
        { title: "Meta Ads — Winchester Launch", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 600, costMid: 1000, costHigh: 3500, selectedCost: 1000, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 6, notes: "Lean launch spend only. Higher spend is stretch/risk." },
        { title: "Google Ads — Winchester Launch", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 300, costMid: 500, costHigh: 2400, selectedCost: 500, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 7, notes: "Lean search launch spend only." },
        { title: "Google Review Acquisition System", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 100, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — David-led", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 8, notes: "Review acquisition process for Winchester." },
        { title: "Before & After Content Bank Creation", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — internal", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 9, notes: "Build content bank pre-launch." },
        { title: "Winchester Local Partnerships Outreach", owner: "Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "N/A — internal", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 10, notes: "Local brand-building outreach." },
        { title: "Instagram Pre-Launch Campaign", owner: "David + Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — internal", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 11, notes: "4-6 week teaser content." },
        { title: "Existing Client Migration Campaign", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — internal", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 12, notes: "Email/SMS/WhatsApp campaign to existing clients." },
        { title: "Referral Programme Setup", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 300, costHigh: 300, selectedCost: 300, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 13, notes: "Referral structure and launch messaging." },
        { title: "Email Campaign to 600 Existing Bedhampton Clients", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "N/A — internal", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 14, notes: "Migration/launch email campaign." },
        { title: "Local PR / Founder Story Campaign", owner: "David + Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 300, costHigh: 300, selectedCost: 300, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 15, notes: "Local awareness/story campaign." },
        { title: "Soft Launch Event", owner: "David + Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 150, costHigh: 500, selectedCost: 150, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 16, notes: "Lean invite-only soft launch." },
        { title: "Professional Photography of Completed Clinic", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 500, costHigh: 862, selectedCost: 500, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 17, notes: "Completed clinic photography for website/ads/GBP." },
      ],
    },
    {
      phase: { name: "Handover, Snagging & Opening", description: "Snagging, certificates, deep clean and opening", sortOrder: 10, status: "active" },
      tasks: [
        { title: "Contractor Handover Pack", owner: "Contractor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — included in contractor package", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 1, notes: "Electrical certs, plumbing details, fire door info, warranties, as-builts, flooring specs, paint specs and handover evidence." },
        { title: "Building Regulations Completion Certificate", owner: "Building Control / Approved Inspector", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "included in Building Control allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "Included inside another package", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 2, notes: "Completion sign-off. Cost captured in Building Control line." },
        { title: "Snagging Inspection and Defects Close-Out", owner: "David + Abi + Contractor", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 500, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — admin/sign-off task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "high", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Final payment should not be released until critical snags and certificates are resolved." },
        { title: "Professional Deep Clean Before Clinical Setup", owner: "Specialist Cleaner / Abi", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 250, costMid: 250, costHigh: 800, selectedCost: 250, isNonNegotiable: true, isCriticalRisk: false, costVatStatus: "inc VAT planning allowance", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 4, notes: "Post-works clean before stock and full clinical setup." },
        { title: "Soft Launch Readiness", owner: "Abi + David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 0, selectedCost: 0, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "N/A — admin task", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "£0 admin task", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 5, notes: "Final go/no-go before opening." },
      ],
    },
    {
      phase: { name: "Deferred / Stretch Items", description: "Items deferred from approved launch cap", sortOrder: 11, status: "active" },
      tasks: [
        { title: "Healthcare Specialist Accountant", owner: "David", status: "deferred", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 2400, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "deferred / not in launch cap", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "low", budgetStatus: "Deferred / not in launch cap", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 1, notes: "Do not include in launch cap unless manually activated." },
        { title: "Business Continuity Plan — Paid Support", owner: "David", status: "deferred", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 600, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "deferred / not in launch cap", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Deferred / not in launch cap", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 2, notes: "Create internally first." },
        { title: "Additional Retail / Skincare Stock Upgrade", owner: "Abi", status: "deferred", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 7000, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "deferred / not in launch cap", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Deferred / not in launch cap", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 3, notes: "Additional retail stock beyond £1,000 opening lean allowance." },
        { title: "FF&E / Styling Upgrade Reserve", owner: "Abi + David", status: "deferred", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 7000, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "deferred / not in launch cap", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Deferred / not in launch cap", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 4, notes: "Only activate if core launch budget allows." },
        { title: "Marketing Spend Upgrade", owner: "David", status: "deferred", riskLevel: "low", costTier: "mid", costLow: 0, costMid: 0, costHigh: 4000, selectedCost: 0, isNonNegotiable: false, isCriticalRisk: false, costVatStatus: "deferred / not in launch cap", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "medium", budgetStatus: "Deferred / not in launch cap", includeInLaunchBudget: false, includeInRiskView: true, sortOrder: 5, notes: "Additional ad spend above lean launch budget." },
      ],
    },
    {
      phase: { name: "Project Contingency", description: "Controlled contingency reserve", sortOrder: 12, status: "active" },
      tasks: [
        { title: "Contingency Reserve — Controlled by David", owner: "David", status: "not_started", riskLevel: "low", costTier: "mid", costLow: 2000, costMid: 3000, costHigh: 10000, selectedCost: 3000, isNonNegotiable: true, isCriticalRisk: true, costVatStatus: "mixed", supplyScope: "to_confirm", procurementStatus: "to_specify", priority: "critical", budgetStatus: "Included in approved launch budget", includeInLaunchBudget: true, includeInRiskView: true, sortOrder: 1, notes: "Contingency reserve for unexpected build, legal or compliance costs. Controlled by David only." },
      ],
    },
  ];

  let totalTasks = 0;
  for (const { phase, tasks } of PHASES) {
    const [newPhase] = await db
      .insert(schema.phasesTable)
      .values({ ...phase, projectId })
      .returning();

    for (const task of tasks) {
      await db.insert(schema.tasksTable).values({ ...task, phaseId: newPhase.id });
    }
    totalTasks += tasks.length;
    console.log(`  ✅ Phase ${phase.sortOrder}: ${phase.name} (${tasks.length} tasks)`);
  }

  await db.execute(
    sql`UPDATE property_task_overrides o
        SET selected_cost = 0, status = NULL
        WHERE o.property_id IN (
          SELECT id FROM properties WHERE project_id = ${projectId}
        )
        AND o.task_id IN (
          SELECT t.id FROM launch_tasks t
          JOIN launch_phases p ON p.id = t.phase_id
          WHERE p.project_id = ${projectId}
          AND p.status = 'archived'
          AND t.status = 'superseded'
        )`
  );

  console.log(`🎉 V8 migration complete: 12 phases, ${totalTasks} tasks`);
}
